### ISSUE TITLE
Push BIM Files to Git repo action failing

### ISSUE THREAD

**Issue by bibinbastian** [gbrueckl/PowerBI.CICD#2]
HI @gbrueckl  Thanks for the great content. I am trying to set it up in Azure Devops and using Devops Git Repo. But looks like there is some permission I am missing and getting this error. Do you know how can I add this permission 

```
remote: 001f# service=git-receive-pack
remote: 0000000000aaTF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\9ae909ca-d00d-4819-ad4a-736f9b355ad8', scope 'repository'.
remote: TF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\9ae909ca-d00d-4819-ad4a-736f9b355ad8', scope 'repository'.
fatal: unable to access 'https://dev.azure.com/Demo233/Test12/_git/Test12/': The requested URL returned error: 403
```

**Comment by bibinbastian** [comment]
It was the Project Collection Build Service permission missing. Adding that to user resolved the issue

**Comment by gbrueckl** [comment]
Great it works now!
kindly let me know if you encounter any other issues - I am really interested in feedback from the field
